destination/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.DestinationListView.as_view(), name='destination-list'),
    path('<int:pk>/', views.DestinationDetailView.as_view(), name='destination-detail'),
    path('create/', views.DestinationCreateView.as_view(), name='destination-create'),
    path('<int:pk>/update/', views.DestinationUpdateView.as_view(), name='destination-update'),
    path('<int:pk>/delete/', views.DestinationDeleteView.as_view(), name='destination-delete'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.say_hello)
]

japanguide/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('destination/', include('destination.urls')),
    path('guide/', include('guide.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: 
    urlpatterns += staticfiles_urlpatterns()

destination/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from ckeditor.fields import RichTextField

# Create your models here.

def tag_default():
    return {"list": []}

class Destination(models.Model):
    REGION_CHOICES = [
        ('TO', 'Tokyo'),
        ('KA', 'Kansai'),
        ('TK', 'Tohoku'),
        ('HK', 'Hokkaido'),
        ('KY', 'Kyushu'),
        ('SK', 'Shikoku'),
    ]
    LOCATION_CHOICES = [
        # Tokyo Areas
        ('UAA', 'Ueno/Asakusa/Akihabara'),
        ('IKE', 'Ikebukuro'),
        ('SNK', 'Shinjuku/Nakano/Kichioji'),
        ('ARO', 'Asakasa/Roppongi'),
        ('SHS', 'Shibuya/Harajuku/Shimokitazawa'),
        ('SME', 'Shinagawa/Meguro/Ebisu'),
        # Kansai Areas
        ('KYT', 'Kyoto'),
        # Hokkaido
        ('SAP', 'Sapporo'),
    ]
    name = models.CharField(max_length=100)
    #image = models.CharField(max_length=200, default="https://i.ibb.co/RvmN9CH/Biwako-Sunset.jpg")
    image = models.URLField(max_length=200, default="https://i.ibb.co/RvmN9CH/Biwako-Sunset.jpg")
    map_link = models.URLField(max_length=200, default="https://www.google.com/maps")
    description = RichTextField(blank=True, null=True)
    region = models.CharField(max_length=2, choices=REGION_CHOICES, default=REGION_CHOICES[0])
    location = models.CharField(max_length=3, choices=LOCATION_CHOICES, default=LOCATION_CHOICES[0])
    rating = models.IntegerField(default=5, validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    tags = models.JSONField("tags", default=tag_default)

    def get_absolute_url(self):
        return reverse("destination-detail", kwargs={"pk": self.pk})
    

destination/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from .models import Destination

class DestinationModelForm(forms.ModelForm):
    class Meta:
        model = Destination
        fields = [
            'name',
            'description',
            'rating',
            'region',
            'location',
            'map_link',
            'image',
            'tags',
        ]

# This form is broken, using previous on because it works now
# class DestinationRawForm(forms.Form):
#     name = forms.CharField()
#     description = forms.CharField(widget=CKEditorWidget())
#     rating = forms.IntegerField()
#     region = forms.CharField()
#     location = forms.CharField()

destination/views.py
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import (
    ListView,
    UpdateView,
)


from .models import Destination
from .forms import DestinationModelForm
# Create your views here.

class DestinationCreateView(View):
    template_name = 'destination/destination_create.html'
    queryset = Destination.objects.all()
    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('home-page')
        context = {'form': DestinationModelForm}
        return render (request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('home-page')
        form = DestinationModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('destination-list')
        context = {'form': self.form_class}
        return render (request, self.template_name, context)
        

class DestinationDetailView(View):
    template_name = 'destination/destination_detail.html'
    def get(self, request, pk=None, *args, **kwargs):
        context = {}
        if pk is not None:
            obj = get_object_or_404(Destination, pk=pk)
            context['object'] = obj
        return render(request, self.template_name, context)


class DestinationListView(ListView):
    template_name = 'destination/destination_list.html'
    queryset = Destination.objects.all()


class DestinationUpdateView(UpdateView):
    template_name = 'destination/destination_create.html'
    def get_object(self):
        pk = self.kwargs.get('pk')
        obj = None
        if pk is not None:
            obj = get_object_or_404(Destination, pk=pk)
        return obj

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('home-page')
        obj = self.get_object()
        context = {
            'object': obj,
            'form': DestinationModelForm(instance=obj),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('home-page')
        obj = self.get_object()
        form = DestinationModelForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
        context = {'form': form, 'object': obj}
        return render (request, self.template_name, context)

# class DestinationUpdateView(UpdateView):
#     template_name = 'destination/destination_create.html'
#     form_class = DestinationModelForm
#     queryset = Destination.objects.all()

#     def get_object(self):
#         id_ = self.kwargs.get("pk")
#         return get_object_or_404(Destination, pk=id_)

#     def form_valid(self, form):
#         return super().form_valid(form)


class DestinationDeleteView(View):
    template_name = 'destination/destination_delete.html'
    def get(self, request, pk=None, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('home-page')
        context = {}
        if pk is not None:
            obj = get_object_or_404(Destination, pk=pk)
            context['object'] = obj
        return render(request, self.template_name, context)
    
    def post(self, request, pk=None, *args, **kwargs):
        if not request.user.is_staff:
            return redirect('home-page')
        if pk is not None:
            obj = get_object_or_404(Destination, pk=pk)
            obj.delete()
            return redirect('../../')
        return render(request, self.template_name, {})

templates/destination/destination_create.html
{% extends 'base.html' %}

{% block content %}

<h1 class="title is-4">Destination Form</h1>
<form class="box has-background-light" action='.' method='POST'> {% csrf_token %}
    {{form.media}}
    {% for field in form %}
    <div class="block m-2">
        {{field.errors}}
        <p>
            {{field.label_tag}} 
        </p>
        {{field}}
        {% if field.help_text %}
        <p>{{field.help_text|safe}}</p>
        {% endif %}
    </div>
    {% endfor %}
    <div class="block">
        <input class="button is-primary" type="submit" value="Save"/>
        <a class="button is-link is-outlined has-text-dark" href="{{object.get_absolute_url}}">Return</a>
    </div>
</form>

{% endblock content %}

{% load static %}
<script type="text/javascript" src="{%static "ckeditor/ckeditor-init.js"%}"></script>
<script type="text/javascript" src="{%static "ckeditor/ckeditor/ckeditor.js"%}"></script>

templates/destination/destination_delete.html
{% extends 'base.html' %}

{% block content %}

<form action="." method="POST"> {% csrf_token %}
    <h1>Do you want to delete the destination: "{{object.name}}"?</h1>
    <p><input type="submit" value="Yes"/> <a href="../">Cancel</a></p>
</form>


{% endblock content %}

templates/destination/destination_detail.html
{% extends 'base.html' %}

{% block content %}
<h1 class="title">{{object.name}}</h1>
<div class="box has-background-light">
    <div class="columns">
        <div class="column">
            <figure class="image">
                <img src="{{object.image}}" alt="Error: Image not found" border="0">
            </figure>
        </div>
        <div class="column">
            <div class="block">
                <p class="title is-5">Rating: {{object.rating}}/5</p>
            </div>
            <div class="block">
                <p class="title is-5">Region: {{object.get_region_display}}</p>
            </div>
            <div class="block">
                <p class="title is-5">Location: {{object.get_location_display}}</p>
            </div>
            <div class="block">
                <p class="title is-5">Maps Link: </p>
                <a class="button is-link" href="{{object.map_link}}">Google Maps</a>
            </div>
            <div class="block">
                <p class="title is-5">Tags:</p>
                {% for tag in object.tags.list %}
                    <p class="button is-info">{{tag}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <p class="title is-5">Description:</p>
    <p>{{object.description|safe}}</p>
</div>

{% endblock content %}

templates/destination/destination_list.html
{% extends 'base.html' %}

{% block content %}

{% load mathtags %}

<h1 class="title">Destination List</h1>
    {% for instance in object_list %}
    {% if forloop.first  or forloop.counter|modulo:4 == 1%}
    <div class="columns">
    {% endif %}
        <div class="column">
            <div class="box has-background-light">
                <div class="columns">
                    <div class="column">
                        <div class="block">
                        <p class="title is-5">{{instance.name}}</p>
                        </div>
                        <p>{{instance.get_location_display}}</p>
                    </div>
                    <div class="column is-narrow">
                        <a 
                            class="button has-background-primary has-text-light" 
                            href="{{instance.get_absolute_url}}"
                        >
                            Info
                        </a>
                    </div>
                </div>
                <div class="block">
                    <figure class="image">
                        <img src="{{instance.image}}" alt="Error: Image not found" border="0" width="300px" height="auto">
                    </figure>
                </div>
            </div>
        </div>
    {% if forloop.counter|modulo:4 == 0 or forloop.last%}
    </div>
    {% endif %}
    {% endfor %}

{% endblock content %}